# Generated by Django 5.0.7 on 2024-07-17 21:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contact",
            name="picture",
            field=models.ImageField(blank=True, upload_to="pictures/%Y/%m/%d"),
        ),
        migrations.AddField(
            model_name="contact",
            name="show",
            field=models.BooleanField(default=True),
        ),
    ]
