# Generated by Django 5.0.7 on 2024-07-21 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0004_alter_category_options_contact_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(blank=True, max_length=250),
        ),
    ]
